language: go
services:
  - docker
script:
- make build
- test -f bin/linux_amd64/workerpodautoscaler
- make all-container
- docker images | grep "^practodev/workerpodautoscaler.*__linux_amd64"
- make test
