apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workerpodautoscaler 
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
- apiGroups:
  - k8s.practo.dev
  resources:
  - workerpodautoscalers 
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - create
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - update
