apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workerpodautoscalers.k8s.practo.dev
spec:
  conversion:
    strategy: None
  group: k8s.practo.dev
  names:
    kind: WorkerPodAutoScaler
    listKind: WorkerPodAutoScalerList
    plural: workerpodautoscalers
    shortNames:
    - wpa
    - wpas
    singular: workerpodautoscaler
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            required:
            - deploymentName
            - minReplicas
            - maxReplicas
            - queueURI
            - targetMessagesPerWorker
            properties:
              deploymentName:
                type: string
                description: 'Name of the kubernetes deployment in the same namespace as WPA object'
              maxDisruption:
                type: string
                description: 'Amount of disruption that can be tolerated in a single scale down activity. Number of pods or percentage of pods that can scale down in a single down scale down activity'
              maxReplicas:
                type: integer
                format: int32
                description: 'Maximum number of workers you want to run'
              minReplicas:
                type: integer
                format: int32
                description: 'Minimum number of workers you want to run'
              queueURI:
                type: string
                description: 'Full URL of the queue'
              targetMessagesPerWorker:
                type: integer
                format: int32
                description: 'Number of jobs in the queue which have not been picked up by the workers. This also used to calculate the desired number of workers'
              secondsToProcessOneJob:
                type: number
                format: float
                description: 'This metric is useful to calculate the desired number of workers more accurately. It is particularly very useful for workers which have `targetMessagesPerWorker` as always zero. `secondsToProcessOneJob` in the combination with `messagesSentPerMinute`(queue RPM) helps in calculating the minimum workers that is expected to be running to handle `messagesSentPerMinute`(RPM) with every job being processed in `secondsToProcessOneJob` seconds'
  - name: v1alpha1
    served: true
    storage: false
