apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: workerpodautoscaler
 namespace: kube-system
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: workerpodautoscaler
   spec:
     serviceAccountName: workerpodautoscaler
     tolerations:
     - effect: NoExecute
       operator: Exists
     - effect: NoSchedule
       operator: Exists
     containers:
     - name: wpa
       env:
       - name: AWS_ACCESS_KEY_ID
         value: {{ WPA_AWS_ACCESS_KEY_ID }}
       - name: AWS_SECRET_ACCESS_KEY
         value: {{ WPA_AWS_SECRET_ACCESS_KEY }}
       image: practodev/workerpodautoscaler:v0.2.0-9-g79201d7
       imagePullPolicy: Always
       command:
       - /workerpodautoscaler
       - run
       - --resync-period=20
       - --wpa-threads=10
       - --aws-region={{ WPA_AWS_REGION }}
       - --sqs-short-poll-interval=20
       - --sqs-long-poll-interval=20
       resources:
         limits:
           cpu: 100m
           memory: 100Mi
         requests:
           cpu: 10m
           memory: 20Mi
